version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 0
  ignore:
  - dependency-name: probot
    versions:
    - 11.1.0
    - 11.2.1
    - 11.2.3
  - dependency-name: nock
    versions:
    - 13.0.10
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
